version: "3.9"

services:
  db:
    image: 'postgres'
    container_name: db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
  sftp:
    image: atmoz/sftp
    ports:
      - "22:22"
    command: foo:pass:::upload