version: "3.9"

services:
  db_storage:
    image: 'postgres'
    container_name: db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
  sftp:
    image: atmoz/sftp
    volumes:
      - .docker/upload:/home/foo/upload
    ports:
      - "10022:22"
    command: foo:pass:::upload